### ISSUE TITLE
Tracking issue for new functionality and design ideas

### ISSUE THREAD

**Issue by rgommers** [numpy/numpy.org#266]
Since we've got a ton of work and conversation going on, I think it's useful to have an overview of ideas we have that are not yet implemented. There's no way we can do all of this before launch; for many of these we can choose to either release them one by one, or do a second significant release:

- [ ] translations (gh-55)
- [ ] new logo (gh-37)
- [ ] install widget (gh-212)
- [ ] further install docs improvements (e.g. unify build from source)
- [ ] interactive shell improvements
- [ ] better Hugo/Sphinx integration (`scipy-sphinx-theme-v2`)
- [ ] search box (gh-263)
- [ ] adding back the array computing content in some form
- [ ] moving the Team gallery to a Hugo template
- [ ] further optimizing categories in the main navigation bar (gh-234)
- [ ] a page on how to report issues (gh-72)
- [ ] content to address some of the user stories we haven't fully taken care of (gh-42)

... and more

**Comment by bjnath** [comment]
Great list! Also:

- [ ] What to do with "Get Started" (gh-244)
